---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: "Download python-meld3 from {{ supervisor_download_url }}/python-meld3-0.6.10-1.el7.x86_64.rpm"
  when: run_once_per_host 
  get_url:
    url: "{{ supervisor_download_url }}/python-meld3-0.6.10-1.el7.x86_64.rpm"
    dest: "{{ path_public_packages }}/python-meld3-0.6.10-1.el7.x86_64.rpm"
    mode: '0711'

- name: "Download supervisord from {{ supervisor_download_url }}/supervisor-{{ supervisor_version }}-1.el7.noarch.rpm"
  when: run_once_per_host 
  get_url:
    url: "{{ supervisor_download_url }}/supervisor-{{ supervisor_version }}-1.el7.noarch.rpm"
    dest: "{{ path_public_packages }}/supervisor-{{ supervisor_version }}-1.el7.noarch.rpm"
    mode: '0711'


- name: Install python-meld3-0.6.10-1.el7.x86_64
  command: "rpm -ivh {{ path_public_packages }}/python-meld3-0.6.10-1.el7.x86_64.rpm --nodeps --force"
  register: python_meld3_install
  ignore_errors: yes

- name: Install supervisor 3.4.0
  command: "rpm -ivh {{ path_public_packages }}/supervisor-3.4.0-1.el7.noarch.rpm --nodeps --force"
  register: supervisor_install
  ignore_errors: yes
