---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Prepare required dirs
  import_tasks: directories.yml

- name: Download python27
  import_tasks: install-python27.yml

- name: Download Supervisor
  import_tasks: download.yml

- name: Configure Supervisor
  import_tasks: configure.yml
