---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- import_tasks: init/main.yml

#- debug: msg={{ steps }}

- include_tasks: "{{ step }}/main.yml"
  loop: "{{ steps | difference(skip_steps) }}"
  loop_control:
    loop_var: step

- name: Check service running status
  when: ansible_play_hosts_all|map('extract', hostvars)|selectattr('ansible_host', 'eq', ansible_host)|map(attribute='inventory_hostname')|list|first == inventory_hostname
  shell: >-
    cd {{ supervisor_path_home }} && supervisorctl -c {{ supervisor_path_home }}/supervisord.conf status | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" | grep -E "({{ service_names|join('|') }})" || true
  register: result_running 

- name: Make running status as a list
  when: run_once_on_present
  set_fact:
    output: >-
      {{ output +
        ['', '###################', '# Running Status #', '###################'] +
        (groups['elasticsearch'] |
         map('extract', hostvars, ['result_running']) |
         select('defined') |
         map(attribute='stdout_lines') |
         select('defined') |
         sum(start=[]) |
         map('regex_replace',':'~project_name~'[^:]+?', ' ') | list
        )
      }}

- name: Summary
  when: run_once_on_present
  debug: var=output

