---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- block:
    - name: Check number of nodes in the cluster
      when: not skip_action_api|bool
      shell: "curl -k -u '{{ es_exec_username }}:{{ es_exec_password }}'  -m 10 '{{ es_address }}/_cat/nodes?h=name' | wc -l"
      register: nodes_count

    - name: Turn off shard allocation
      when: not skip_action_api|bool
      shell: "curl -k -u '{{ es_exec_username }}:{{ es_exec_password }}' -m 10 -XPUT {{ es_address }}/_cluster/settings -H 'Content-Type: application/json' -d '{\"transient\" : {\"cluster.routing.allocation.enable\" : \"primaries\" }}'"
      register: response
      retries: 30
      delay: 2
      until: response.stdout.find('"acknowledged":true') != -1
      failed_when: response.stdout.find('"acknowledged":true') == -1

    - name: Perform a synced-flush
      when: not skip_action_api|bool
      ignore_errors: true
      shell: "curl -k -u '{{ es_exec_username }}:{{ es_exec_password }}' -m 10 -XPOST {{ es_address }}/_flush/synced"

    - name: Stop the elasticsearch service
      import_tasks: "action-stop.yml"

    - name: Start the elasticsearch service
      import_tasks: "action-start.yml"

    - name: Wait for the node to rejoin the cluster
      when: not skip_action_api|bool
      shell: "curl -k -u '{{ es_exec_username }}:{{ es_exec_password }}' -m 10 '{{ es_address }}/_cat/nodes?h=name' | wc -l"
      register: new_nodes
      until: new_nodes.stdout == nodes_count.stdout
      retries: 200
      delay: 3

    - name: Turn on shard allocation
      when: not skip_action_api|bool
      shell: "curl -k -u '{{ es_exec_username }}:{{ es_exec_password }}' -m 10 -XPUT {{ es_address }}/_cluster/settings -H 'Content-Type: application/json' -d '{\"transient\" : {\"cluster.routing.allocation.enable\" : null }}'"
      register: response
      retries: 30
      delay: 2
      until: response.stdout.find('"acknowledged":true') != -1
      failed_when: response.stdout.find('"acknowledged":true') == -1

    - name: Wait until cluster status is green
      when: not skip_action_api|bool
      shell: "curl -k -u '{{ es_exec_username }}:{{ es_exec_password }}' -m 10 -XGET {{ es_address }}/_cluster/health"
      register: response
      until: response.stdout.find('"status":"green"') != -1
      retries: 8640
      delay: 10
  any_errors_fatal: true

