---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

# installing java

- name: Check jdk already downloaded
  when: run_once_per_host
  stat:
    path: "{{ path_public_packages }}/{{ jdk_filename.dir }}"
  register: result_downloaded

- name: "Download jdk from {{ jdk_download_url }}/{{ jdk_filename.base }}.tar.gz"
  when: run_once_per_host and result_downloaded.stat.exists == false
  get_url:
    url: "{{ jdk_download_url }}/{{ jdk_filename.base }}.tar.gz"
    dest: "{{ path_tmp }}/{{ jdk_filename.base }}.tar.gz"

- name: Unarchive jdk
  when: run_once_per_host and result_downloaded.stat.exists == false
  unarchive:
    owner: "{{ running_user | default(ansible_user_id) }}"
    src: "{{ path_tmp }}/{{ jdk_filename.base }}.tar.gz"
    dest: "{{ path_public_packages }}"
    remote_src: true

- name: Create symbolic link
  file:
    owner: "{{ running_user | default(ansible_user_id) }}"
    src: "{{ path_public_packages }}/{{ jdk_filename.dir }}"
    dest: "{{ jdk_path_home }}"
    state: link
