---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

presented_inventory_on_host: "{{ ansible_play_hosts_all|map('extract', hostvars)|selectattr('ansible_host', 'eq', ansible_host)|selectattr('state', 'undefined')|map(attribute='inventory_hostname')|list + ansible_play_hosts_all|map('extract', hostvars)|selectattr('ansible_host', 'eq', ansible_host)|selectattr('state', 'defined')|selectattr('state', 'eq', 'present')|map(attribute='inventory_hostname')|list }}"
run_once_per_host: "{{ presented_inventory_on_host|length > 0 and (presented_inventory_on_host|first == inventory_hostname) }}"
presented_inventory: "{{ (ansible_play_hosts_all|map('extract', hostvars)|selectattr('state', 'undefined')|list + ansible_play_hosts_all|map('extract', hostvars)|selectattr('state', 'defined')|selectattr('state', 'eq', 'present')|list)|map(attribute='inventory_hostname') }}"
run_once_on_present: "{{ presented_inventory|length > 0 and (presented_inventory|first == inventory_hostname) }}"
