---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

# vars file for jdk

supervisor_version: 3.4.0
supervisor_download_url: https://s3.cn-north-1.amazonaws.com.cn/puxiang-public-packages/repos/supervisord/bin
supervisor_http_port: 9010

path_base: /opt/elk
path_public_packages: "{{ path_base }}/packages"
path_tmp: "{{ path_base }}/tmp"

supervisor_path_home: "{{ path_base }}/supervisor"
supervisor_path_conf: "{{ supervisor_path_home }}/conf.d"
supervisor_path_logs: "{{ supervisor_path_home }}/logs"

supervisor_use_systemd: true
supervisor_service_name: supervisord
supervisorctl_name: supervisorctl
