---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- block:
    - name: Generate temp password
      when: es_exec_password is not defined
      set_fact:
        es_exec_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

    - name: Generate temp user
      shell: "source {{ path_env }} && {{ path_home }}/elasticsearch/bin/elasticsearch-users userdel {{ es_exec_username }} || true && {{ path_home }}/elasticsearch/bin/elasticsearch-users useradd {{ es_exec_username }} -p {{ es_exec_password }} -r superuser"
  any_errors_fatal: true
