# - name: Check service status
#   command: "{{ supervisor_path_home }}/supervisord -c {{ supervisor_path_home }}/supervisord.conf ctl status {{ service_name }}"
#   register: result_service_status

# - name: Do start
#   when: result_service_status.stdout.lower().find('running') == -1 and result_service_status.stdout.lower().find('starting') == -1
#   command: "{{ supervisor_path_home }}/supervisord -c {{ supervisor_path_home }}/supervisord.conf ctl start {{ service_name }}"


- name: Check service status
  shell: "cd {{ supervisor_path_home }} && supervisorctl -c {{ supervisor_path_home }}/supervisord.conf  status {{ service_name }}"
  register: result_service_status

- name: Do start
  when: result_service_status.stdout.find('RUNNING') == -1 and result_service_status.stdout.find('STARTING') == -1
  shell: "cd {{ supervisor_path_home }} && supervisorctl -c {{ supervisor_path_home }}/supervisord.conf  start {{ service_name }}"

