---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Do stop
  ignore_errors: true
  command: "{{ supervisor_path_home }}/supervisord -c {{ supervisor_path_home }}/supervisord.conf ctl stop {{ service_name }}"

- name: Do start
  command: "{{ supervisor_path_home }}/supervisord -c {{ supervisor_path_home }}/supervisord.conf ctl start {{ service_name }}"
