---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Action check
  fail: msg="unknown action keyword {{ action }}"
  when: action not in [ 'restart', 'full-restart', 'rolling-restart' ]

- name: Service
  when: is_service_running
  import_tasks: "action-{{ action }}.yml"
