---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Generate temp password
  when: security_item.payload.password is not defined
  set_fact:
    temp_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

- name: Change password for user {{ security_item.params.username }}
  shell: >-
    curl -k -m 10 -u '{{ es_exec_username }}:{{ es_exec_password }}'
    -XPOST {{ es_address }}/_security/user/{{ security_item.params.username }}/_password
    -H 'Content-Type: application/json'
    -d '{"password" : "{{ security_item.payload.password | default( temp_password ) }}"}'
  register: response
  retries: 30
  delay: 2
  until: response.stdout == '{}'

- name: Append to Output
  set_fact:
    output: "{{ output + [' user: '~security_item.params.username~'    password: '~(security_item.payload.password|default( temp_password ))~' '] }}"
