---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Create or update user {{ security_item.params.username }}
  shell: >-
    curl -k -m 10 -u '{{ es_exec_username }}:{{ es_exec_password }}'
    -XPOST {{ es_address }}/_security/user/{{ security_item.params.username }}
    -H 'Content-Type: application/json'
    -d '{{ security_item.payload | to_json }}'
  register: response
  retries: 30
  delay: 2
  until: response.stdout.find('created') != -1

- name: Append to output
  when: security_item.payload.password is defined
  set_fact:
    output: "{{ output + [' user: '~security_item.params.username~'    password: '~security_item.payload.password~' '] }}"
