---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

output: []
filename: "kibana-{{ '' if not use_oss|bool or version is version('6.3.0', '<') else 'oss-' }}{{ version }}-linux-x86_64.tar.gz"
presented_inventory_on_host: "{{ ansible_play_hosts_all|map('extract', hostvars)|selectattr('ansible_host', 'eq', ansible_host)|selectattr('state', 'undefined')|map(attribute='inventory_hostname')|list + ansible_play_hosts_all|map('extract', hostvars)|selectattr('ansible_host', 'eq', ansible_host)|selectattr('state', 'defined')|selectattr('state', 'eq', 'present')|map(attribute='inventory_hostname')|list }}"
run_once_per_host: "{{ presented_inventory_on_host|length > 0 and (presented_inventory_on_host|first == inventory_hostname) }}"
presented_inventory: "{{ (ansible_play_hosts_all|map('extract', hostvars)|selectattr('state', 'undefined')|list + ansible_play_hosts_all|map('extract', hostvars)|selectattr('state', 'defined')|selectattr('state', 'eq', 'present')|list)|map(attribute='inventory_hostname')|list }}"
run_once_on_present: "{{ presented_inventory|length > 0 and (presented_inventory|first == inventory_hostname) }}"
xpack: "{{ (version is version('6.3.0', '>=') and not use_oss|bool) or 'xpack' in (plugins|map(attribute='name')|list) }}"
is_service_deployed: false
is_service_running: false
kibana_address: "{{ server_host }}:{{ server_port | default(5601) }}"
kibana_hosts: >-
  [{% for host in (ansible_play_hosts_all|map('extract', hostvars)|selectattr('state', 'undefined')|list + ansible_play_hosts_all|map('extract', hostvars)|selectattr('state', 'defined')|selectattr('state', 'eq', 'present')|list) %}
  "http://{{ host['server_host'] if 'server_host' in host else host['ansible_host'] }}:{{ host['server_port'] if 'server_port' in host else '5601' }}"{{ ',' if not loop.last else '' }}
  {% endfor %}]
service_names: >-
  [{% for host in (groups['kibana'] | map('extract', hostvars) | list) %}
  "{{ host['service_name'] | default(host['project_name']~'-'~host['inventory_hostname']) }}"{{ ',' if not loop.last else '' }}
  {% endfor %}]
