---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

version: 7.9.2
download_url: https://s3.cn-north-1.amazonaws.com.cn/puxiang-public-packages/repos/kibana/tar     # https://artifacts.elastic.co/downloads/kibana
use_oss: false
node_name: "{{ [project_name, 'kibana', ansible_hostname] | select('defined') | select('ne', '') | join('-') }}"
# Plugins
#  - name: ~
#    url: ~
plugins: []
