---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.3           更新日期:2024-05-16
#
#
#===============================================================================================

- name: Do elasticsearch-stop-all
  hosts: "{{ hosts | default('elasticsearch') }}"
  tasks:
   - name: Print copyright information
     run_once: true
     debug: 
      msg: "{{['###########################################################', 
      '#                                                         #', 
      '#  Yogoo ELK Ansible Automation Deployment V1.5           #', 
      '#  Copyright 2020-2024 Shanghai Yogoo Software Co., Ltd.  #',
      '#                                                         #',
      '#  www.yogoo.net                                          #',
      '#                                                         #', 
      '###########################################################']  }}"

- name: Setup elasticsearch
  hosts: "{{ hosts | default('elasticsearch') }}"
  serial: "{{ 1 if action is defined and action == 'rolling-restart' else '100%' }}"
  roles:
    - role: elasticsearch
      vars:
        skip_steps:
          - system
          - install
          - plugin
          - configure
          - temp-user/create
          - check
          - temp-user/clear
        action: stop

