---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-06
#
#
#===============================================================================================

- name: Do elk-setup
  hosts: "{{ hosts | default('elasticsearch') }}"
  tasks:
   - name: Print copyright information
     run_once: true
     debug: 
      msg: "{{['###########################################################', 
      '#                                                         #', 
      '#  Yogoo ELK Ansible Automation Deployment V1.5           #', 
      '#  Copyright 2020-2024 Shanghai Yogoo Software Co., Ltd.  #',
      '#                                                         #',
      '#  www.yogoo.net                                          #',
      '#                                                         #', 
      '###########################################################']  }}"

- name: Setup elasticsearch
  hosts: "{{ hosts | default('elasticsearch') }}"
  roles:
    - role: elasticsearch
      vars:
        added_steps:
          - turn-on-monitoring
          - security
        security_init: true
        security_payloads:
          - action: change-password
            params:
              username: kibana
            payload:
              password: "{{ kibana_password | default('kibana_password') }}"
          - action: change-password
            params:
              username: logstash_system
            payload:
              password: "{{ logstash_monitoring_password | default('logstash_monitoring_password') }}"
          - action: change-password
            params:
              username: beats_system
            payload:
              password: "{{ beats_monitoring_password | default('beats_monitoring_password') }}"
          - action: upsert-user
            params:
              username: logstash_admin
            payload:
              password: "{{ logstash_management_password | default('logstash_management_password') }}"
              roles: ["logstash_admin", "logstash_system"]
              full_name: "logstash_admin"
              email: "logstash_admin@{{ project_name }}.com"
          - action: change-password
            params:
              username: elastic

- name: Setup logstash
  hosts: "{{ hosts | default('logstash') }}"
  roles:
    - role: logstash

- name: Setup logstash
  hosts: "{{ hosts | default('kibana') }}"
  roles:
    - role: kibana
