---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Turn on xpack monitoring
  when: xpack|bool and run_once_on_present
  shell: >-
    curl -k -m 10 -u '{{ es_exec_username }}:{{ es_exec_password }}'
    -XPUT {{ es_address }}/_cluster/settings
    -H 'Content-Type: application/json'
    -d '{"persistent": { "xpack.monitoring.collection.enabled": true }}'
  register: response
  retries: 30
  delay: 2
  until: response.stdout.find('"acknowledged":true') != -1
