---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

version: 7.9.2
download_url: https://s3.cn-north-1.amazonaws.com.cn/puxiang-public-packages/repos/elasticsearch/tar   # https://artifacts.elastic.co/downloads/elasticsearch
use_oss: false                # set if use an oss version without xpack, xpack features will be auto disabled
#java_home:                   # set a path if you have custom jdk
force_extra_jdk: false        # if true, bundled jdk will never be used
node_name: "{{ [project_name, zone, inventory_hostname, ansible_hostname] | select('defined') | select('ne', '') | join('-') }}"
#ca_pass: ''                  # set a ca pass to protect your ca
#ca_file_url:                 # set a ca file url, otherwise ca will be auto generated and kept in {{path_local_store}}/{{project_name}}/elastic-stack-ca.p12
# Plugins                     # plugins to install, leave url empty to download from official site
#  - name: ~
#    url: ~
plugins: []
remove_plugins: []
