---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

path_base: /opt/elk
path_tmp: "{{ path_base }}/tmp"
path_project: "{{ path_base }}/{{ project_name }}"
path_packages: "{{ path_project }}/packages" 
path_libs: "{{ path_project }}/libs/elasticsearch"
path_home: "{{ path_project }}/elasticsearch/{{ inventory_hostname }}"
path_env:  "{{ path_home }}/env.sh"
#path_heap_dump

path_conf: "{{ path_home }}/config"
path_logs: "{{ path_home }}/logs"
path_data: "{{ path_home }}/data"

supervisor_path_home: "{{ path_base }}/supervisor"
supervisor_path_conf: "{{ supervisor_path_home }}/conf.d"
