---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2020 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.0.0           更新日期:20200820
#
#
#===============================================================================================

- name: Generate CA file update
  when: run_once_on_present and ca_file_url is not defined 
  shell: |
    rm -f {{ path_conf }}/certs/elastic-stack-ca.p12 && \
    source {{ path_env }} && {{ path_home }}/elasticsearch/bin/elasticsearch-certutil ca --out {{ path_conf }}/certs/elastic-stack-ca.p12 --pass '{{ ca_pass | default('') }}'

- name: Fetch generated ca file from remote update
  when: run_once_on_present and ca_file_url is not defined 
  fetch:
    flat: true
    src: "{{ path_conf }}/certs/elastic-stack-ca.p12"
    dest: "{{ path_local_store }}/{{ project_name }}/elastic-stack-ca.p12"

- name: Copy ca file update
  when: ca_file_url is not defined
  copy:
    src: "{{ path_local_store }}/{{ project_name }}/elastic-stack-ca.p12"
    dest: "{{ path_conf }}/certs"

- name: Download CA file update
  when: ca_file_url is defined
  get_url:
    url: "{{ ca_file_url }}"
    dest: "{{ path_conf }}/certs/elastic-stack-ca.p12"
    force: yes

- name: Generate certificate update
  args:
    warn: false
  shell: |
    rm -f {{ path_conf }}/certs/elastic-certificates.p12 && \
    source {{ path_env }} && {{ path_home }}/elasticsearch/bin/elasticsearch-certutil cert \
    --ca {{ path_conf }}/certs/elastic-stack-ca.p12 \
    --ca-pass '{{ ca_pass | default('') }}' \
    --ip {{ server_host }} \
    --pass '' \
    --days {{ ca_days | default(730) }} \ 
    --out {{ path_conf }}/certs/elastic-certificates.p12 && \
    chmod +x {{ path_conf }}/certs/elastic-stack-ca.p12 && \
    chmod +x {{ path_conf }}/certs/elastic-certificates.p12 && \
    chown -R {{running_user}}:{{running_user}} {{path_conf}}
    
