---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2020 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.0.0           更新日期:20200820
#
#
#===============================================================================================

- name: Generate certificates
  when: xpack|bool and xpack_security|bool
  import_tasks: certificate.yml
