---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- import_tasks: check/main.yml

- import_tasks: system/main.yml
  when: "'system' not in skip_steps and state != 'absent'"

- import_tasks: install/main.yml
  when: "'install' not in skip_steps and state != 'absent'"

- import_tasks: configure/main.yml
  when: "'configure' not in skip_steps and state != 'absent'"

- name: Initialize service
  import_tasks: service/main.yml

- name: Ensure state
  when: is_service_deployed
  import_tasks: service/state/main.yml

- name: Execute action
  when: action is defined and state == 'present'
  include_tasks: service/action/main.yml

- name: Check node running
  when: state == 'present'
  wait_for:
    host: "{{ server_host }}"
    port: "{{ server_port }}"
    timeout: 120

- name: Check service running status
  when: ansible_play_hosts_all|map('extract', hostvars)|selectattr('ansible_host', 'eq', ansible_host)|map(attribute='inventory_hostname')|list|first == inventory_hostname
  shell: >-
    cd {{ supervisor_path_home }} && supervisorctl -c {{ supervisor_path_home }}/supervisord.conf status | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" | grep -E "({{ service_names|join('|') }})" || true
  register: result_running

- name: Make running status as a list
  when: run_once_on_present
  set_fact:
    output: >-
      {{ output +
        ['', '###################', '# Running Status #', '###################'] +
        (groups['kibana'] |
         map('extract', hostvars, ['result_running']) |
         select('defined') |
         map(attribute='stdout_lines') |
         select('defined') |
         sum(start=[]) |
         map('regex_replace',':'~project_name~'[^:]+?', ' ') | list
        )
      }}

- name: Summary
  when: run_once_on_present
  debug: var=output
