---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Template kibana supervisor config file
  template:
    src: supervisor/kibana.conf.j2
    dest: "{{ supervisor_path_conf }}/{{ service_name }}.conf"

- name: Set es hosts
  when: es_hosts is not defined and 'elasticsearch' in groups
  set_fact:
    es_hosts: >-
      [{% for host in (groups['elasticsearch'] | map('extract', hostvars) | list) %}
      {% if (host['state'] is undefined or host['state'] == 'present') and (host['roles'] is undefined or 'coordinating' in host['roles']) %}
      "{{ 'https' if xpack|bool and xpack_security|bool and xpack_security_https|bool else 'http' }}://{{ host['server_host'] if 'server_host' in host else host['ansible_host'] }}:{{ host['http_port'] if 'http_port' in host else '9200' }}"{{ ',' if not loop.last else '' }}
      {% endif %}
      {% endfor %}]

- name: Create logs directory
  file:
    owner: "{{ running_user | default(ansible_user_id) }}"
    path: "{{ path_logs }}"
    state: directory

- name: Template kibana config file
  template:
    src: kibana.yml.j2
    dest: "{{ path_conf }}/kibana.yml"

- name: Change file permission for running user
  when: running_user is defined
  file:
    owner: "{{ running_user }}"
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - "{{ path_home }}"
    - "{{ path_conf }}"
    - "{{ path_logs }}"

- name: Set kibana hosts output
  when: run_once_on_present
  set_fact:
    output: "{{ output + ['', '###################', '# kibana addresses #', '###################'] + kibana_hosts }}"
