---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================


- name: Populate service facts
  service_facts:

- name: stop iptables
  when: "'iptables.service' in services"
  service:
    name: iptables
    enabled: false
    state: stopped

- name: stop firewalld
  when: "'firewalld.service' in services"
  service:
    name: firewalld
    enabled: false
    state: stopped

- name: Stop selinux
  args:
    warn: false
  shell: sed -ri s/enforcing/disabled/ /etc/selinux/config && setenforce 0 || true
