---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Check elasticsearch already downloaded
  when: run_once_per_host
  stat:
    path: "{{ path_packages }}/elasticsearch-{{ version }}"
  register: result_downloaded

- name: "Download elasticsearch from {{ download_url }}/{{ filename }}"
  when: run_once_per_host and result_downloaded.stat.exists == false
  get_url:
    url: "{{ download_url }}/{{ filename }}"
    dest: "{{ path_tmp }}/{{ filename }}"
    #url_username: "{{ url_username }}"
    #url_password: "{{ url_password }}"

- name: Unarchive elasticsearch
  when: run_once_per_host and result_downloaded.stat.exists == false
  unarchive:
    owner: "{{ running_user | default(ansible_user_id) }}"
    src: "{{ path_tmp }}/{{ filename }}"
    dest: "{{ path_packages }}"
    remote_src: true

- name: Create symbolic link
  file:
    owner: "{{ running_user | default(ansible_user_id) }}"
    src: "{{ path_packages }}/elasticsearch-{{ version }}"
    dest: "{{ path_home }}/elasticsearch"
    state: link
