---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Symbolic elasticsearch bundled jdk
  when: java_home is not defined and version is version('7.0.0', '>=') and not force_extra_jdk|bool
  file:
    owner: "{{ running_user | default(ansible_user_id) }}"
    src: "{{ path_home }}/elasticsearch/jdk"
    dest: "{{ path_home }}/jdk"
    state: link

- name: Check to install jdk
  when: java_home is not defined and (version is version('7.0.0', '<') or force_extra_jdk|bool)
  include_role:
    name: jdk
  vars:
    - jdk_path_home: "{{ path_home }}/jdk"

- name: Configure Envs
  blockinfile:
    path: "{{ path_env }}"
    create: true
    block: |
      export JAVA_HOME={{ java_home | default(path_home~'/jdk') }}
      export ES_PATH_CONF={{ path_conf }}
