---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Add running user
  when: run_once_per_host and running_user is defined
  user:
    name: "{{ running_user }}"

- name: Create directories
  import_tasks: directory.yml

- name: Download elasticsearch
  import_tasks: download.yml

- name: Setup JDK
  import_tasks: jdk.yml

- name: Copy default configs
  copy:
    src: "{{ path_home }}/elasticsearch/config"
    dest: "{{ path_home }}"
    remote_src: true

- name: Generate certificates
  when: xpack|bool and xpack_security|bool
  import_tasks: certificate.yml

- name: Setup service
  import_tasks: service.yml
