---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

#jdk_download_url: https://s3.cn-north-1.amazonaws.com.cn/puxiang-public-packages/repos/jdk/tar
jdk_download_url: http://172.168.0.106:8080/elk
jdk_filename:
  base: jdk-11.0.6_linux-x64_bin
  dir: jdk-11.0.6
# base: jdk-8u212-linux-x64
# dir: jdk1.8.0_212

path_base: /opt/elk
path_public_packages: "{{ path_base }}/packages"
path_tmp: "{{ path_base }}/tmp"
jdk_path_home: "{{ path_base }}/jdk"

