---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.0           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Run or reload supervisord
  when: run_once_per_host
  shell: |
    if [ -f {{ supervisor_path_home }}/supervisord.pid ] && ps -p `cat {{ supervisor_path_home }}/supervisord.pid` > /dev/null; then
      cd {{ supervisor_path_home }} && supervisorctl -c {{ supervisor_path_home }}/supervisord.conf reread && supervisorctl -c {{ supervisor_path_home }}/supervisord.conf update
    else
      {% if supervisor_use_systemd|bool %}
      sudo systemctl start supervisord
      {% else %}
      cd {{ supervisor_path_home }} && supervisorctl -c {{ supervisor_path_home }}/supervisord.conf -d
      {% endif %}
    fi
