---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

# tasks file for elasticsearch configure settings

- name: Template elasticsearch config file
  template:
    src: elasticsearch.yml.j2
    dest: "{{ path_conf }}/elasticsearch.yml"

- name: Template jvm.options file
  template:
    src: jvm.options.j2
    dest: "{{ path_conf }}/jvm.options"

- name: Add Keystore Settings
  shell: "source {{ path_env }} && echo {{ item.value }} | {{ path_home }}/elasticsearch/bin/elasticsearch-keystore add {{ item.key }} -xf"
  loop: "{{ keystore }}"

- name: Set es hosts output
  when: run_once_on_present
  set_fact:
    output: "{{ output + ['', '###################', '# es coordinating hosts #', '###################'] + es_hosts }}"
