---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

# Create directories

- name: Create logs directory
  file:
    owner: "{{ running_user | default(ansible_user_id) }}"
    path: "{{ path_logs }}"
    state: directory

- name: Create data directories
  file:
    owner: "{{ running_user | default(ansible_user_id) }}"
    path: "{{ item }}"
    state: directory
  loop: "{{ path_data.split(',') }}"

- name: Create dump directories
  when: path_heap_dump is defined
  file:
    owner: "{{ running_user | default(ansible_user_id) }}"
    path: "{{ path_heap_dump }}"
    state: directory
