---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Create libs subdirs
  file:
    owner: "{{ running_user | default(ansible_user_id) }}"
    path: "{{ path_libs }}/{{ item.filename | dirname }}"
    state: directory
  loop: "{{ libs | selectattr('filename', 'defined') | list }}"

- name: Create settings subdirs
  file:
    owner: "{{ running_user | default(ansible_user_id) }}"
    path: "{{ path_conf }}/{{ item.filename | dirname }}"
    state: directory
  loop: "{{ (settings + template_settings) | selectattr('filename', 'defined') | list }}"

- name: Download libs
  get_url:
    url: "{{ item.url if item is mapping else item }}"
    dest: "{{ path_libs }}/{{ item.filename if item is mapping else ( item | basename ) }}"
    force: yes
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
  loop: "{{ libs }}"

- name: Download settings
  get_url:
    url: "{{ item.url if item is mapping else item }}"
    dest: "{{ path_conf }}/{{ item.filename if item is mapping else ( item | basename ) }}"
    force: yes
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
  loop: "{{ settings }}"

- name: Create local template settings dirs
  when: template_settings|length > 0
  become: false
  delegate_to: localhost
  vars:
    ansible_become: false
  file:
    path: "{{ path_local_store }}/{{ project_name }}/{{ inventory_hostname }}/template_settings/{{ item.filename | dirname }}"
    state: directory
  loop: "{{ template_settings | selectattr('filename', 'defined') | list }}"

- name: Download template settings
  become: false
  delegate_to: localhost
  vars:
    ansible_become: false
  get_url:
    url: "{{ item.url if item is mapping else item }}"
    dest: "{{ path_local_store }}/{{ project_name }}/{{ inventory_hostname }}/template_settings/{{ item.filename if item is mapping else ( item | basename ) }}"
    force: yes
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
  loop: "{{ template_settings }}"

- name: Template settings
  template:
    src: "{{ path_local_store }}/{{ project_name }}/{{ inventory_hostname }}/template_settings/{{ item.filename if item is mapping else ( item | basename ) }}"
    dest: "{{ path_conf }}/{{ item.filename if item is mapping else ( item | basename ) }}"
  loop: "{{ template_settings }}"
