---
#===============================================================================================
#
#  悦高软件-- ansible ELK 部署 Playbook
#
#  版权所有（c）2020-2024 上海悦高软件股份有限公司,保留所有权利。
#-----------------------------------------------------------------------------------------------
#  建立日期：2019-09-10
#
#  版 本 号：V1.5.2           更新日期:2024-03-05
#
#
#===============================================================================================

- name: Setup service
  import_tasks: service.yml

- name: Create directories
  import_tasks: directory.yml

- name: Configure Elasticsearch
  import_tasks: configure.yml

- name: Download libs
  import_tasks: libs.yml

- name: Change file permission for running user
  when: running_user is defined
  file:
    owner: "{{ running_user }}"
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - "{{ path_home }}"
    - "{{ path_conf }}"
    - "{{ path_data }}"
    - "{{ path_logs }}"

- name: Setup service
  import_tasks: service.yml
